server:
  port: 8081


spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:      #routes、discovery是两种路由方式，一种是直接根据uri路由，一种是与服务发现组件结合
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
              enabled: true
      routes:     #routers 是根据uri路由的 本示例访问方式： http://Gateway_HOST:Gateway_PORT/order/**  。
      - id: host_route
        uri: http://localhost:8883
        predicates:
        - Path= /order/**
        filters:
        - StripPrefix= 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/

